make dask scheduler type and protocol configurable within a manager
Arbol-Project/gridded-etl-tools pull request #66
Opened 2023-08-29 16:40 UTC by rbanick

2023-08-29 17:34 UTC, ohsqueezy approved these changes

2023-08-30 18:08 UTC, ohsqueezy requested changes
About the base dataset functions,

- All of our transformations are done on base/original sources, so the naming is a bit awkward. Maybe there are some optimizations we can make if we're pulling from our internal S3, but basically this is the same as pulling from any S3, so I think especially for the tools repo, we want something that is generalized to pull from any given S3 url. This actually kind of is that, but the docstring describes it differently.

- Given that these functions are only used by a single manager, I suggest implementing them in the manager before generalizing in the tools library. It would be a good use of the manager's extract function. And since we're refactoring extract, we can then update the manager to use any S3 functions we add to the extract utility we're working on.

2023-08-31 12:54 UTC, rbanick commented on gridded_etl_tools/dataset_manager.py
> +            self.dask_num_threads = multiprocessing.cpu_count() -1
Setting it to `0` will use all available cores. You’re saying you’re OK with that?

2023-08-31 12:55 UTC, rbanick commented on gridded_etl_tools/dataset_manager.py
> +            self.dask_num_threads = multiprocessing.cpu_count() -1
But then should we just have that be the default, always?

2023-08-31 16:27 UTC, ohsqueezy approved these changes

2023-08-31 16:54 UTC, merged